# Generated by Django 4.2.20 on 2025-04-07 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('genre', models.CharField(choices=[('1', 'Mystery'), ('2', 'Comedy'), ('3', 'Thriller')], max_length=3)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('release_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
