# Generated by Django 4.2.20 on 2025-04-07 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('genre', models.CharField(choices=[(1, 'Action'), (2, 'Adventure'), (3, 'Animation'), (4, 'Comedy'), (5, 'Costume drama'), (6, 'Crime'), (7, 'Documentary'), (8, 'Drama'), (9, 'Fantasy'), (10, 'Horror'), (11, 'Musical'), (12, 'Mystery'), (13, 'Romance'), (14, 'Science fiction'), (15, 'Thriller'), (16, 'War'), (17, 'Western')])),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('release_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('plot', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('review', models.TextField(max_length=2000)),
                ('approved', models.BooleanField(default=False)),
                ('rating', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
                ('movie_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movie.movie')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
