# Generated by Django 4.2.20 on 2025-04-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_remove_movie_actors_movie_cast_moviecast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='cast',
            new_name='actors',
        ),
    ]
