# Generated by Django 4.2.20 on 2025-04-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_rename_cast_movie_actors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField()),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='actors',
            new_name='cast',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.DeleteModel(
            name='MovieCast',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='genre', to='movie.genre'),
        ),
    ]
