# Generated by Django 4.2.20 on 2025-04-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_genre_alter_actor_options_alter_director_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(max_length=200),
        ),
    ]
