# Generated by Django 4.2.20 on 2025-04-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_movie_options_alter_movie_movie_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='text',
        ),
    ]
