# Generated by Django 4.2.20 on 2025-04-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_rename_review_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='movie.genre'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
