# Generated by Django 4.2.20 on 2025-04-14 10:23

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_movie_genre_alter_review_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=movie.models.default_approved),
        ),
    ]
