# Generated by Django 4.2.20 on 2025-04-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_movie_genre_alter_review_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
