# Generated by Django 4.2.20 on 2025-04-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_movie_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='top_pick',
            field=models.BooleanField(default=False),
        ),
    ]
