# Generated by Django 4.2.20 on 2025-04-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_movie_top_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='pick_motivation',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
